version: '3.8'

services:
  postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexus_gaming
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: nexus-gaming-next/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/nexus_gaming
      - JWT_SECRET=your-super-secret-key-change-in-production
    depends_on:
      - postgres
    volumes:
      - ./nexus-gaming-next:/app
      - /app/node_modules

volumes:
  postgres-data:
